### ISSUE TITLE
Cannot be used with webpack

### ISSUE THREAD

**Issue by phw** [srfrnk/ua-device-detector#2] opened 2018-01-15 20:32 UTC
To upgrade to ng-device-detector 5 I tried requiring ua-device-detector in my project, which is built with webpack:

```
require('ua-device-detector')
require('ng-device-detector')
```

But webpack fails to require ua-device-detector:

```
WARNING in ./node_modules/ua-device-detector/ua-device-detector.js
456:22-29 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/ua-device-detector/ua-device-detector.js
 @ ./src/common/parolu/ui/clockpicker/clockpicker.js
 @ ./src/app/parolu.localization.js
 @ ./src/app/app.js
 @ ./src/app/app.spec.js
 @ ./src .+\.spec\.js$
 @ ./src/spec.bundle.js
webpack: Compiled with warnings.
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  {
    "message": "Error: Cannot find module \".\"\nat undefined:456:0",
    "str": "Error: Cannot find module \".\"\nat undefined:456:0"
  }
```

**Comment by srfrnk** [comment] 2018-01-16 05:32
Any way you can create a makefile/script or whatever that I can use to replicate the issue?

**Comment by lev-kuznetsov** [comment] 2018-02-21 17:19
Basically it can't deal with https://github.com/srfrnk/ua-device-detector/blob/master/ua-device-detector.js#L456 it looks for someone calling require('') and if it's any other form it will barf. If it's OK to change it to something like:

```
try {
  require("re-tree");
  module.exports = {
    parseUserAgent: function (ua, customDetectors) {
      return parseUserAgent({ reTree: reTree || {}, customDetectors: customDetectors || [], userAgent: ua || "" });
     },
     BROWSERS: BROWSERS,
     DEVICES: DEVICES,
     OS: OS
   };
} catch (error) {}
```
 it should be fine; I can make a PR

**Comment by srfrnk** [comment] 2018-02-22 05:12
Do you have any way for me to replicate this issue on my machine or on-line?
Basically line 456 should check availability of `require` and if it's undefined *not* go into the `if`.
I don't see how the proposed changed solves the issue. It would catch all errors - sure but the code won't run so what's the point? Can you explain?

**Comment by lev-kuznetsov** [comment] 2018-02-22 13:08
I created a minimum project showing the error here: https://github.com/lev-kuznetsov/ua-det-webpack-error

Checkout, `npm i` and `npm run build` to see the error. Webpack does static code analysis and that's not a syntax they recognize. Because reasons. I know it looks like a warning but angularjs module won't work.

**Comment by lev-kuznetsov** [comment] 2018-02-26 14:26
I'm still getting an error when I'm trying to use it in angular:

```
Uncaught Error: Cannot find module "."
    at webpackMissingModule (ua-device-detector.js:551)
    at ua-device-detector.js:551
    at Object.<anonymous> (ua-device-detector.js:562)
    at Object.webpackEmptyContext.keys (ua-device-detector.js:562)
```

line 551 is the same `!!require` line. I'm going to try and update my minimal app to an angular app so that you can see it, but I'm swamped at the moment it may not be for a couple of days

**Comment by srfrnk** [comment] 2018-02-26 14:34
Sure - No problem I won't have any time to work on that until the weekend for sure.
Keep me updated when I can replicate the issue and I'll take a look.

**Comment by dobesv** [comment] 2018-04-14 17:01
This might be fixed now, as long as you import re-tree yourself first.

**Comment by srfrnk** [comment] 2018-04-14 17:10
Could you maybe confirm this?

**Comment by dobesv** [comment] 2018-04-16 22:01
I don't have any webpack experience. @lev-kuznetsov can you try it out ?

**Comment by tbhardwaj** [comment] 2018-05-16 12:23
any update on this issue? I am facing the same issue with web pack at line# 551 is the same !!require line. If we remove !!require  from if condition then it works fine.

**Comment by dobesv** [comment] 2018-05-17 07:54
Did you try the new workaround, which is to import re-tree prior to importing this module?  And follow the instructions here: https://github.com/srfrnk/ua-device-detector/commit/9a01ef3dd1694a26a13d2e5aad7c46b135065670

**Comment by srfrnk** [comment] 2018-05-17 07:59
@dobesv I think I will try fixing this issue when I can. while the workaround works for angular - react projects might need ui-device-detector. Don't you agree?
But if anyone has more experience with webpack I'd gladly accept any help.

**Comment by srfrnk** [comment] 2018-05-18 15:00
@lev-kuznetsov Can you please test again?
Followed your instructions and got:
```bash
Now using node v9.11.1 (npm v5.6.0)
***:~/tmp/ua-det-webpack-error$ npm i
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ua-det-webpack-error@1.0.0 No description
npm WARN ua-det-webpack-error@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 4.217s
***:~/tmp/ua-det-webpack-error$ npm run build

> ua-det-webpack-error@1.0.0 build /***/tmp/ua-det-webpack-error
> webpack

Hash: 95204586bf73971bffb8
Version: webpack 3.11.0
Time: 750ms
    Asset     Size  Chunks             Chunk Names
bundle.js  59.9 kB       0  [emitted]  main
   [0] (webpack)/buildin/module.js 517 bytes {0} [built]
   [1] ./index.js 28 bytes {0} [built]
   [4] ./node_modules/ua-device-detector 160 bytes {0} [built]
    + 3 hidden modules
```

Maybe this was fixed in latest versions of webpack?

**Comment by tbhardwaj** [comment] 2018-05-18 19:35
@dobesv I tried importing re-tree prior to importing this however that did not work for me. 
I used require block in try and that did a workaround for me. 
try { require('ua-device-detector'); } catch (e) { console.log(e.code) }

@srfrnk probably its fixed with Webpack 3.0, I was trying with Webpack 2.2.1, Thanks for looking into it.

**Comment by srfrnk** [comment] 2018-05-20 08:01
@tbhardwaj Thanks for the update. Is there any reason to try and fix this for an older version or can I just close this issue?

**Comment by simonemazzoni** [comment] 2018-07-18 11:07
@srfrnk I had the same problem using webpack 3.5.5
I had to use the old 4.0.3 version of ng-device-detector, a fix would be nice.

**Comment by srfrnk** [comment] 2018-07-28 15:14
Hi @simonemazzoni ,
Can you please clone and run @lev-kuznetsov's repo: https://github.com/lev-kuznetsov/ua-det-webpack-error ?
It looks like the latest version works well.
If you still have a problem can you fork this and change to match your issue or create an example code that demonstrates your issue?

**Comment by simonemazzoni** [comment] 2018-07-31 12:38
@srfrnk the webpack-error project works well since it aims to solely include the ua-device-detector lib.
My problem actually happens using ng-device-detector in my angularjs app. I wrote here since the error seems to be caused by an incorrect import of ua-device-detector lib in ng-device-detector.

![screen shot 2018-07-31 at 14 33 37](https://user-images.githubusercontent.com/3217537/43459833-1af8c132-94cf-11e8-9098-c38dabefb75f.png)

I don't understand exactly whats the reason. But this new version with external ua-device-detector lib seems not work in angularjs apps.

Could you please investigate further?

**Comment by srfrnk** [comment] 2018-07-31 13:15
Can you be more specific? Which angular version? How do you import the module?
If you could create share your code I could look into it.

**Comment by simonemazzoni** [comment] 2018-07-31 13:43
@srfrnk 
Nothing special actually. I simply do an import and then I declare the module as I do for all the other modules included the v4.0.3 of ng-device-detector.
```
import 'ng-device-detector';
angular.module('app', ['ng.deviceDetector']);
```

And when I load my angular app, it complains that `Module uaDeviceDetector is not available!`

**Comment by srfrnk** [comment] 2018-08-15 08:16
HI @simonemazzoni - Sorry for the delay.
I've cloned an angular 1.5 seed repo and added ng-device-detector.
It looks like you issue cannot be replicated there.
PLease take a look at it:
https://github.com/srfrnk/angular-seed

If you could replicate the problem there I might be able to help.
If not maybe you can share more details on how exactly you're using it.
I noticed you're 'importing' the code. Does that mean you're using webpack or something similar?
Can you create a repo with the basics that shows what you're doing and the issue?

**Comment by simonemazzoni** [comment] 2018-08-29 09:37
@srfrnk sorry for the late answer, I missed the notification email.

I tried your angular-seed project and it works, but I also see that you included `ua-device-detector` as an html `<script>` in the index.html file. So you basically import only the `ng-device-detector` lib with the ES6 syntax, hence that test isn't useful.

I guess the fact is that the `ng-device-detector` is exported correctly, but the `ua-device-detector` and `retree` packages are not. hence that when I try to import ng-device-detector I get the error that says that `uaDeviceDetector` cannot bene instantiated.

The point is then that version 4.0.3 work well.

**Comment by srfrnk** [comment] 2018-08-29 10:58
No worries.
Can you maybe fork the code and show me how you would like things to be?
Might be possible for me to make it so.
Thx.

**Comment by simonemazzoni** [comment] 2018-08-29 15:31
@srfrnk I investigated a little and I found the bug.

The bug is in this line [https://github.com/srfrnk/ua-device-detector/blob/master/ua-device-detector.js#L551](https://github.com/srfrnk/ua-device-detector/blob/master/ua-device-detector.js#L551)

I created a [PR](https://github.com/srfrnk/ua-device-detector/pull/7), please let me know it is ok and can be merged.

**Comment by srfrnk** [comment] 2018-08-30 04:47
@simonemazzoni Thx! Great catch! PR merged.

**Comment by simonemazzoni** [comment] 2018-08-30 16:52
@srfrnk, @phw I confirm you that the new version works correctly!

I just had to add also `import ua-device-detector` in my code right before `ng-device-detector`

**Comment by srfrnk** [comment] 2018-09-01 17:07
Great @simonemazzoni 
I'm going to close the issue then.
Many thanx

**Closed as completed by srfrnk** 2018-09-01 17:07 UTC
